"""add sport to bout_subscriptions

Revision ID: 8df6f9297a34
Revises: f7a0001_devices
Create Date: 2026-07-24 12:32:36.169860

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df6f9297a34'
down_revision: Union[str, None] = 'f7a0001_devices'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bout_subscriptions', sa.Column('sport', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_bout_subscriptions_sport'), 'bout_subscriptions', ['sport'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bout_subscriptions_sport'), table_name='bout_subscriptions')
    op.drop_column('bout_subscriptions', 'sport')
    # ### end Alembic commands ###