"""fase 2b 3 tablas users subscriptions alert_log

Revision ID: a3657c6166f0
Revises: 0001
Create Date: 2026-07-08 14:03:19.207872

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3657c6166f0"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("phone_normalized", sa.String(length=20), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("role", sa.Enum("user", "admin", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "bout_subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=50), nullable=False),
        sa.Column("bout_id", sa.String(length=50), nullable=False),
        sa.Column("target_match_number", sa.Integer(), nullable=False),
        sa.Column("previous_bout_id", sa.String(length=50), nullable=True),
        sa.Column("previous_match_number", sa.Integer(), nullable=True),
        sa.Column("lead_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "fired", "cancelled", name="subscription_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bout_subscriptions_bout_id"), "bout_subscriptions", ["bout_id"], unique=False
    )
    op.create_index(
        op.f("ix_bout_subscriptions_event_id"), "bout_subscriptions", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_bout_subscriptions_status"), "bout_subscriptions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_bout_subscriptions_user_id"), "bout_subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "event_subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=50), nullable=False),
        sa.Column("event_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_subscriptions_event_id"), "event_subscriptions", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_subscriptions_user_id"), "event_subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "sport_subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("sport", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sport_subscriptions_sport"), "sport_subscriptions", ["sport"], unique=False
    )
    op.create_index(
        op.f("ix_sport_subscriptions_user_id"), "sport_subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "alert_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("subscription_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("bout_id", sa.String(length=50), nullable=False),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fired_at_hour", sa.Integer(), nullable=False),
        sa.Column("payload", sa.String(length=2000), nullable=True),
        sa.Column("notifier_response", sa.String(length=500), nullable=True),
        sa.Column(
            "status", sa.Enum("fired", "failed", "skipped", name="alert_status"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subscription_id"], ["bout_subscriptions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subscription_id", "bout_id", "fired_at_hour", name="uq_alert_idempotency"
        ),
    )
    op.create_index(op.f("ix_alert_log_bout_id"), "alert_log", ["bout_id"], unique=False)
    op.create_index(op.f("ix_alert_log_fired_at"), "alert_log", ["fired_at"], unique=False)
    op.create_index(
        op.f("ix_alert_log_subscription_id"), "alert_log", ["subscription_id"], unique=False
    )
    op.create_index(op.f("ix_alert_log_user_id"), "alert_log", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alert_log_user_id"), table_name="alert_log")
    op.drop_index(op.f("ix_alert_log_subscription_id"), table_name="alert_log")
    op.drop_index(op.f("ix_alert_log_fired_at"), table_name="alert_log")
    op.drop_index(op.f("ix_alert_log_bout_id"), table_name="alert_log")
    op.drop_table("alert_log")
    op.drop_index(op.f("ix_sport_subscriptions_user_id"), table_name="sport_subscriptions")
    op.drop_index(op.f("ix_sport_subscriptions_sport"), table_name="sport_subscriptions")
    op.drop_table("sport_subscriptions")
    op.drop_index(op.f("ix_event_subscriptions_user_id"), table_name="event_subscriptions")
    op.drop_index(op.f("ix_event_subscriptions_event_id"), table_name="event_subscriptions")
    op.drop_table("event_subscriptions")
    op.drop_index(op.f("ix_bout_subscriptions_user_id"), table_name="bout_subscriptions")
    op.drop_index(op.f("ix_bout_subscriptions_status"), table_name="bout_subscriptions")
    op.drop_index(op.f("ix_bout_subscriptions_event_id"), table_name="bout_subscriptions")
    op.drop_index(op.f("ix_bout_subscriptions_bout_id"), table_name="bout_subscriptions")
    op.drop_table("bout_subscriptions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
